# Summer Lloyd Sonde Calculations

In [1]:
# testing hysteresis parameter calculation? 
import numpy as np
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import matplotlib.dates as mdates

shear_stress = pd.read_csv('data/shear_stress/average_total_shear_stress_corrected.csv', parse_dates=['datetime'], index_col='datetime')
gw_head = pd.read_csv('data/groundwater/groundwater_head_full.csv', parse_dates=['Date_Time'], index_col='Date_Time')
sonde_downstream = pd.read_csv('data/sonde_data/sonde_down_full_record_smoothed.csv', parse_dates=['DateTime'], index_col='DateTime')
sonde_upstream = pd.read_csv('data/sonde_data/sonde_up_full_record_smoothed.csv', parse_dates=['DateTime'], index_col='DateTime')

Process and Merge Data

In [2]:
# average rows with duplicate timestamps on sonde data (second-resolution data)
sonde_downstream = sonde_downstream.groupby(level=0).mean(numeric_only=True)
sonde_upstream = sonde_upstream.groupby(level=0).mean(numeric_only=True)

# re-sample shear stress and sonde data to 1 min intervals
shear_stress = shear_stress.resample('1min').interpolate()
groundwater_head = gw_head.resample('1min').interpolate()
sonde_downstream_resampled = sonde_downstream.resample('1min').interpolate()
sonde_upstream_resampled = sonde_upstream.resample('1min').interpolate()

# also join the sonde data with the shear stress data for the entire record 
sonde_downstream = sonde_downstream.join(shear_stress['shear_stress'], how="left")
sonde_upstream = sonde_upstream.join(shear_stress['shear_stress'], how="left")
# also join the sonde data with the groundwater head data for the entire record
sonde_downstream = sonde_downstream.join(groundwater_head['P123_h_average'], how="left")
sonde_upstream = sonde_upstream.join(groundwater_head['P123_h_average'], how="left")

Hysteresis index calculation functions

In [3]:
def normalize_storm_df(df, tau_col, constituent_cols, cols_to_normalize=None):
    out = df.copy()

    if cols_to_normalize is None:
        cols_to_normalize = [tau_col] + [c for c in constituent_cols if c in out.columns]

    for col in cols_to_normalize:
        if col not in out.columns:
            continue

        series = out[col].astype(float)
        smin = series.min(skipna=True)
        smax = series.max(skipna=True)

        if pd.isna(smin) or pd.isna(smax) or smax == smin:
            out[col] = np.nan
        else:
            out[col] = (series - smin) / (smax - smin)

    return out

def split_hydrograph(df, tau_col, constituent_col):
    ts = df[[tau_col, constituent_col]].dropna().sort_index()
    if ts.empty:
        return None, None, None

    peak_pos = ts[tau_col].to_numpy().argmax()
    peak_label = ts.index[peak_pos]

    rise = ts.iloc[:peak_pos + 1][[tau_col, constituent_col]]
    fall = ts.iloc[peak_pos:][[tau_col, constituent_col]]  # exclude the peak point from the falling limb
    return rise, fall, peak_label

def interpolate_time_at_tau(tau_target, limb_df, tau_col, allow_extrapolate=True, fit_points=4):
    if limb_df is None or limb_df.empty:
        return None

    limb = limb_df[[tau_col]].dropna().sort_index()
    if len(limb) == 0:
        return None
    if len(limb) == 1:
        return limb.index[0]

    tau = limb[tau_col].to_numpy(dtype=float)
    t = limb.index.view("int64")

    exact = np.where(tau == tau_target)[0]
    if exact.size > 0:
        return limb.index[exact[0]]

    diffs = tau - tau_target
    crossings = np.where(diffs[:-1] * diffs[1:] <= 0)[0]

    if crossings.size > 0:
        i = crossings[0]
        tau0, tau1 = tau[i], tau[i + 1]
        t0, t1 = t[i], t[i + 1]
    else:
        if not allow_extrapolate:
            return None

        n = min(fit_points, len(tau))
        if n < 2:
            return limb.index[-1]

        if tau_target < np.nanmin(tau):
            tau_fit = tau[:n]
            t_fit = t[:n]
        else:
            tau_fit = tau[-n:]
            t_fit = t[-n:]

        if np.all(tau_fit == tau_fit[0]):
            return pd.to_datetime(int(t_fit[0]))

        slope, intercept = np.polyfit(tau_fit, t_fit, 1)
        t_target = slope * tau_target + intercept
        return pd.to_datetime(int(t_target))

    if tau1 == tau0:
        return pd.to_datetime(int(t0))

    t_target = t0 + (t1 - t0) * ((tau_target - tau0) / (tau1 - tau0))
    return pd.to_datetime(int(t_target))

def get_time_bracket_points(t_target, limb_df, tau_col, constituent_col, allow_extrapolate=True, fit_points=4):
    if limb_df is None or limb_df.empty:
        return None

    limb = limb_df[[tau_col, constituent_col]].dropna().sort_index()
    if len(limb) < 2:
        return None

    t = limb.index.view("int64")
    tau = limb[tau_col].to_numpy(dtype=float)
    c = limb[constituent_col].to_numpy(dtype=float)
    t_target_int = pd.Timestamp(t_target).value

    extrapolated = False

    if t[0] <= t_target_int <= t[-1]:
        upper_idx = np.searchsorted(t, t_target_int, side="right")
        lower_idx = max(upper_idx - 1, 0)
        upper_idx = min(upper_idx, len(t) - 1)
    elif not allow_extrapolate:
        return None
    else:
        n = min(fit_points, len(t))
        if n < 2:
            return None

        extrapolated = True
        if t_target_int < t[0]:
            lower_idx, upper_idx = 0, n - 1
        else:
            lower_idx, upper_idx = len(t) - n, len(t) - 1

    return {
        "t0": pd.to_datetime(int(t[lower_idx])),
        "t1": pd.to_datetime(int(t[upper_idx])),
        "tau0": tau[lower_idx],
        "tau1": tau[upper_idx],
        "c0": c[lower_idx],
        "c1": c[upper_idx],
        "extrapolated": extrapolated,
    }

def interpolate_constituent_at_time(t_target, limb_df, constituent_col, allow_extrapolate=True):
    if limb_df is None or limb_df.empty:
        return np.nan

    limb = limb_df[[constituent_col]].dropna().sort_index()
    if len(limb) == 0:
        return np.nan
    if len(limb) == 1:
        return limb[constituent_col].iloc[0]

    t = limb.index.view("int64")
    y = limb[constituent_col].to_numpy(dtype=float)
    t_target_int = pd.Timestamp(t_target).value

    if t[0] <= t_target_int <= t[-1]:
        return np.interp(t_target_int, t, y)

    if not allow_extrapolate:
        return np.nan

    if t_target_int < t[0]:
        t0, t1 = t[0], t[1]
        y0, y1 = y[0], y[1]
    else:
        t0, t1 = t[-2], t[-1]
        y0, y1 = y[-2], y[-1]

    if t1 == t0:
        return y0

    slope = (y1 - y0) / (t1 - t0)
    return y0 + slope * (t_target_int - t0)

def get_time_bracket_points(t_target, limb_df, tau_col, constituent_col, allow_extrapolate=True, fit_points=4):
    if limb_df is None or limb_df.empty:
        return None

    limb = limb_df[[tau_col, constituent_col]].dropna().sort_index()
    if len(limb) < 2:
        return None

    t = limb.index.view("int64")
    tau = limb[tau_col].to_numpy(dtype=float)
    c = limb[constituent_col].to_numpy(dtype=float)
    t_target_int = pd.Timestamp(t_target).value

    extrapolated = False

    if t[0] <= t_target_int <= t[-1]:
        upper_idx = np.searchsorted(t, t_target_int, side="right")
        lower_idx = max(upper_idx - 1, 0)
        upper_idx = min(upper_idx, len(t) - 1)
    elif not allow_extrapolate:
        return None
    elif t_target_int < t[0]:
        lower_idx, upper_idx = 0, 1
        extrapolated = True
    else:
        lower_idx, upper_idx = len(t) - 2, len(t) - 1
        extrapolated = True

    return {
        "t0": pd.to_datetime(int(t[lower_idx])),
        "t1": pd.to_datetime(int(t[upper_idx])),
        "tau0": tau[lower_idx],
        "tau1": tau[upper_idx],
        "c0": c[lower_idx],
        "c1": c[upper_idx],
        "extrapolated": extrapolated,
    }

def calculate_lawler_adapted_HI(df, tau_col, constituent_col, storm_name, k=0.5):
    rise, fall, peak_label = split_hydrograph(df, tau_col, constituent_col)
    if rise is None or fall is None or rise.empty or fall.empty:
        print(f"Not enough data points to split the hydrograph for {storm_name} {constituent_col}")
        return None

    tau_min = df[tau_col].min()
    tau_max = df[tau_col].max()
    tau_mid = k * (tau_max - tau_min) + tau_min

    t_rise_mid = interpolate_time_at_tau(tau_mid, rise, tau_col, allow_extrapolate=True)
    t_fall_mid = interpolate_time_at_tau(tau_mid, fall, tau_col, allow_extrapolate=True)

    if t_rise_mid is None or t_fall_mid is None:
        print(f"Could not find target time for storm {storm_name} {constituent_col}")
        return None

    c_rise = interpolate_constituent_at_time(t_rise_mid, rise, constituent_col, allow_extrapolate=True)
    c_fall = interpolate_constituent_at_time(t_fall_mid, fall, constituent_col, allow_extrapolate=True)

    if np.isnan(c_rise) or np.isnan(c_fall):
        print(f"Could not interpolate storm {storm_name} {constituent_col}")
        return None

    rise_bracket = get_time_bracket_points(t_rise_mid, rise, tau_col, constituent_col)
    fall_bracket = get_time_bracket_points(t_fall_mid, fall, tau_col, constituent_col)

    if c_rise > c_fall:
        HI = 1 - (c_fall / c_rise)
    elif c_rise < c_fall:
        HI = -1 + (c_rise / c_fall)
    else:
        HI = 0

    return {
        "storm_name": storm_name,
        "HI": HI,
        "tau_mid": tau_mid,
        "c_rise": c_rise,
        "c_fall": c_fall,
        "rise": rise,
        "fall": fall,
        "tau_col": tau_col,
        "constituent_col": constituent_col,
        "k": k,
        "t_rise_mid": t_rise_mid,
        "t_fall_mid": t_fall_mid,
        "rise_bracket": rise_bracket,
        "fall_bracket": fall_bracket,
        "peak_label": peak_label,
    }

def calculate_lloyd_HI(df, tau_col, constituent_col, storm_name, k=0.5):
    rise, fall, peak_label = split_hydrograph(df, tau_col, constituent_col)
    if rise is None or fall is None or rise.empty or fall.empty:
        print(f"Not enough data points to split the hydrograph for {storm_name} {constituent_col}")
        return None

    tau_min = df[tau_col].min()
    tau_max = df[tau_col].max()
    tau_mid = k * (tau_max - tau_min) + tau_min

    t_rise_mid = interpolate_time_at_tau(tau_mid, rise, tau_col, allow_extrapolate=True)
    t_fall_mid = interpolate_time_at_tau(tau_mid, fall, tau_col, allow_extrapolate=True)

    if t_rise_mid is None or t_fall_mid is None:
        print(f"Could not find target time for storm {storm_name} {constituent_col}")
        return None

    c_rise = interpolate_constituent_at_time(t_rise_mid, rise, constituent_col, allow_extrapolate=True)
    c_fall = interpolate_constituent_at_time(t_fall_mid, fall, constituent_col, allow_extrapolate=True)

    if np.isnan(c_rise) or np.isnan(c_fall):
        print(f"Could not interpolate storm {storm_name} {constituent_col}")
        return None

    rise_bracket = get_time_bracket_points(t_rise_mid, rise, tau_col, constituent_col)
    fall_bracket = get_time_bracket_points(t_fall_mid, fall, tau_col, constituent_col)

    HI = c_rise - c_fall

    return {
        "storm_name": storm_name,
        "HI": HI,
        "tau_mid": tau_mid,
        "c_rise": c_rise,
        "c_fall": c_fall,
        "rise": rise,
        "fall": fall,
        "tau_col": tau_col,
        "constituent_col": constituent_col,
        "k": k,
        "t_rise_mid": t_rise_mid,
        "t_fall_mid": t_fall_mid,
        "rise_bracket": rise_bracket,
        "fall_bracket": fall_bracket,
        "peak_label": peak_label,
    }

def plot_lloyd_hysteresis_multi_k(results_list, df, tau_col, constituent_col,
                                    xlabel=r"Shear Stress ($\tau$)",
                                    ylabel="Constituent",
                                    out_dir="HI_calculations/lawler_plots",
                                    save=True,
                                    show=False):

    if results_list is None or len(results_list) == 0:
        return

    results_list = sorted(results_list, key=lambda r: r.get("k", 0.5))

    storm_name = results_list[0].get("storm_name", "")
    ts_df = df[[tau_col, constituent_col]].dropna().sort_index()

    fig, axes = plt.subplots(1, 2, figsize=(10, 5), gridspec_kw={"width_ratios": [1.2, 1]})

    # Colors for the different k values
    cmap = plt.get_cmap("viridis")
    color_values = np.linspace(0.15, 0.85, len(results_list))

    # Left panel: time series with horizontal threshold lines for each k
    ax = axes[0]
    ax.plot(ts_df.index, ts_df[tau_col], color="tab:blue", linewidth=1.5, label=tau_col)
    ax.set_ylabel(tau_col, color="tab:blue")
    ax.tick_params(axis="y", labelcolor="tab:blue")
    ax.xaxis.set_major_locator(MaxNLocator(8))

    ax2 = ax.twinx()
    ax2.plot(ts_df.index, ts_df[constituent_col], color="tab:red", linewidth=1.5, label=constituent_col)
    ax2.set_ylabel(constituent_col, color="tab:red")
    ax2.tick_params(axis="y", labelcolor="tab:red")

    for result in results_list:
        tau_mid = result["tau_mid"]
        k = result.get("k", 0.5)
        ax.axhline(
            tau_mid,
            linestyle="--",
            color="gray",
            alpha=0.7,
            linewidth=1.3,
            label=fr"$\tau_{{mid}}$ (k={k:.1f})"
        )

    peak_label = results_list[0].get("peak_label")
    if peak_label is not None and peak_label in ts_df.index:
        tau_peak = ts_df.at[peak_label, tau_col]
        ax.scatter(peak_label, tau_peak, marker="*", color="k", s=160, zorder=9)

    event_date = ts_df.index[0].strftime("%Y-%m-%d")
    ax.set_title(f"Event time series ({event_date})")
    ax.set_xlabel("Time (HH:MM)")
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=4, maxticks=8))
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
    ax.grid(True, alpha=0.3)

    # Right panel: hysteresis plot with one gray vertical line per k
    ax = axes[1]
    point_size = 35

    rise = results_list[0]["rise"]
    fall = results_list[0]["fall"]

    combined = pd.concat([rise, fall.iloc[1:]])
    ax.plot(combined[tau_col], combined[constituent_col], color="black", linewidth=2, alpha=0.6, zorder=1)

    # Base points: no black edges here
    ax.scatter(rise[tau_col], rise[constituent_col], color="gray", s=point_size,
                label="Rising limb", zorder=4, edgecolor="none")
    ax.scatter(fall[tau_col], fall[constituent_col], color="gray", s=point_size,
                label="Falling limb", zorder=4, edgecolor="none")

    for result in results_list:
        tau_mid = result["tau_mid"]
        c_rise = result["c_rise"]
        c_fall = result["c_fall"]
        k = result.get("k", 0.5)

        ax.axvline(
            tau_mid,
            linestyle="--",
            color="gray",
            linewidth=1.5,
            alpha=0.7,
            label=fr"$\tau_{{mid}}$ (k={k:.1f})"
        )

        # Only the tau_target points get black edges
        ax.scatter(tau_mid, c_rise, s=point_size, color="forestgreen",
                    edgecolor="black", linewidth=1.2, zorder=6)
        ax.scatter(tau_mid, c_fall, s=point_size, color="firebrick",
                    edgecolor="black", linewidth=1.2, zorder=6)

    if peak_label is not None and peak_label in ts_df.index:
        tau_peak = ts_df.at[peak_label, tau_col]
        c_peak = ts_df.at[peak_label, constituent_col]
        ax.scatter(tau_peak, c_peak, marker="*", color="k", s=160, zorder=9, edgecolor="black")

    ax.set_xlabel(xlabel, fontsize=12)
    ax.set_ylabel(ylabel, fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.set_title("Lawler HI across k values")

    main_title = f"{storm_name} - {constituent_col} Hysteresis" if storm_name else f"{constituent_col} Hysteresis"
    fig.suptitle(main_title, fontsize=15)
    fig.tight_layout(rect=[0, 0, 1, 0.95])

    if save:
        os.makedirs(out_dir, exist_ok=True)
        safe_name = f"{storm_name}_{constituent_col}_lawler_multi_k.png".replace(" ", "_").replace("/", "_")
        fig.savefig(os.path.join(out_dir, safe_name), dpi=300, bbox_inches="tight")

    if show:
        plt.show()

    plt.close(fig)

Separating storm by date and time

In [5]:
# define storm windows once
storm_windows = {
    "st1_down": ("2021-07-23 12:30", "2021-07-28 11:15"),
    "st1_up":   ("2021-07-23 12:30", "2021-07-28 11:15"),
    "st2_down": ("2022-08-03 14:30", "2022-08-03 18:30"),
    "st2_up":   ("2022-08-03 14:30", "2022-08-03 18:30"),
    "st3_down": ("2022-08-08 12:30", "2022-08-08 22:15"),
    "st3_up":   ("2022-08-08 12:30", "2022-08-08 22:15"),
    "st4_down": ("2023-07-29 13:00", "2023-07-30 10:30"),
    "st4_up":   ("2023-07-29 13:00", "2023-07-30 10:30"),
    "st5_down": ("2023-08-13 17:15", "2023-08-14 03:15"),
    "st5_up":   ("2023-08-13 17:15", "2023-08-14 03:15"),
    "st6_down": ("2023-08-28 11:30", "2023-08-28 16:30"),
    "st6_up":   ("2023-08-28 11:30", "2023-08-28 16:30"),
    "st7_down": ("2023-09-14 13:00", "2023-09-15 13:00"),
    "st7_up":   ("2023-09-14 13:00", "2023-09-15 13:00")
}

# build event dictionary directly (no function)
sonde_events = {}
down = sonde_downstream.sort_index()   
up = sonde_upstream.sort_index()      

for storm_name, (start, end) in storm_windows.items():
    start = pd.Timestamp(start)
    end = pd.Timestamp(end)

    if "down" in storm_name.lower():
        src = down
    elif "up" in storm_name.lower():
        src = up
    else:
        continue
    sonde_events[storm_name] = src.loc[(src.index >= start) & (src.index <= end)].copy()

Normalize shear stress and sonde data

In [6]:
sonde_constituents = ["Turbidity FNU", "fDOM RFU", "P123_h_average"]

for storm_name, storm_df in sonde_events.items():
    sonde_events[storm_name] = normalize_storm_df(
        storm_df,
        tau_col="shear_stress",
        constituent_cols=sonde_constituents
    )

### Lawler Adapted:
Turbidity and fDOM hysteresis

Calculate Lawler Adapted HI for sonde data

In [7]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []

    for storm_name, storm_df in sonde_events.items():
        if constituent not in storm_df.columns:
            continue

        row = {"storm": storm_name}

        for k in ks:
            result = calculate_lawler_adapted_HI(
                storm_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=storm_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["storm"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["storm"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("storm").reset_index(drop=True)

        out_path = f"HI_calculations/summer_storms/lawler_adapted_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st1_down,0.472901,-0.704964,-0.327388,0.519563,0.266547,0.314821,0.523868,0.733148,0.635877,0.270486
1,st1_up,0.405917,0.281044,0.321478,0.557689,0.541501,0.611937,0.759808,0.803026,0.716284,0.555409
2,st2_down,-0.343514,0.463770,0.484668,0.488131,0.471150,0.775252,0.685510,0.461731,0.426958,0.434851
3,st2_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,st3_down,-0.611113,-0.342773,0.421085,0.319179,0.156816,0.131176,0.019872,0.179393,0.265304,0.059882
5,st3_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,st4_down,-9.485884,0.384917,0.483166,0.366204,0.258806,0.303456,0.317915,0.239235,0.133697,-0.777610
7,st4_up,-0.741731,0.368086,-0.311039,0.229432,0.529217,0.397178,0.391850,0.286321,0.166292,0.146178
8,st5_down,-0.148863,0.891380,0.797204,0.730011,0.718501,0.689861,0.522118,0.602338,0.618932,0.602387
9,st5_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,st6_down,0.485485,0.576833,0.574962,0.394585,0.406471,0.415619,-0.210870,-0.408263,-0.288382,0.216271
11,st6_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,st7_down,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,st7_up,-0.920092,0.618221,0.603163,0.571096,0.401332,0.395351,0.174144,-0.254099,-0.107245,0.164652

Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st1_down,-0.322283,-0.679610,-0.806083,-0.779427,-0.570476,-0.508217,-0.647376,-0.729414,-0.565296,-0.623131
1,st1_up,-0.145900,-0.617574,-0.752021,-0.711650,-0.574419,-0.549526,-0.648792,-0.745645,-0.601459,-0.594110
2,st2_down,-0.979739,-0.909339,-0.877789,-0.847418,-0.810313,-0.748339,-0.724746,-0.668951,-0.611277,-0.797546
3,st2_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,st3_down,-0.950619,-0.907932,-0.830875,-0.795655,-0.773054,-0.755645,-0.735702,-0.625534,-0.471690,-0.760745
5,st3_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,st4_down,-0.897603,-0.717883,-0.722837,-0.720948,-0.743141,-0.786533,-0.782103,-0.288694,-0.157530,-0.646364
7,st4_up,-0.905796,-0.754625,-0.624853,-0.578743,-0.644458,-0.627960,-0.614341,-0.248003,-0.134037,-0.570313
8,st5_down,-0.984348,-0.317225,-0.245435,-0.172629,-0.120988,-0.089170,-0.090612,0.181431,0.370154,-0.163203
9,st5_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,st6_down,-0.897711,-0.852884,-0.836707,-0.809714,-0.784777,-0.761774,-0.744782,-0.614951,-0.434609,-0.748657
11,st6_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,st7_down,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,st7_up,-0.998631,-0.786650,-0.777010,-0.773328,-0.758948,-0.435196,-0.267673,0.258556,0.120600,-0.490920

Plot sonde data

In [8]:
for storm_name, storm_df in sonde_events.items():
    for constituent in ["Turbidity FNU", "fDOM RFU"]:
        if constituent not in storm_df.columns:
            continue

        results_list = []

        for k in ks:
            result = calculate_lawler_adapted_HI(
                storm_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=storm_name,
                k=k
            )

            if result is not None:
                results_list.append(result)

        if results_list:
            plot_lloyd_hysteresis_multi_k(
                results_list,
                storm_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                out_dir="HI_calculations/summer_storms/lawler_adapted_plots",
                save=True,
                show=False
            )

Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU

Lawler Adapted for groundwater hysteresis

In [9]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []
    for storm_name, storm_df in sonde_events.items():
        results_list = []
        if constituent not in storm_df.columns:
            continue
        # skip if no valid data for this constituent
        if storm_df[constituent].dropna().empty:
            print(f"Skipping {storm_name}: no valid {constituent} data")
            continue

        row = {"storm": storm_name}

        for k in ks:
            result = calculate_lawler_adapted_HI(
                storm_df,
                tau_col="P123_h_average",
                constituent_col=constituent,
                storm_name=storm_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

            if result is not None:
                results_list.append(result)

        if results_list:
            try:
                plot_lloyd_hysteresis_multi_k(
                    results_list,
                    storm_df,
                    tau_col="P123_h_average",
                    constituent_col=constituent,
                    out_dir="HI_calculations/groundwater_hysteresis/summer/lawler_adapted_plots",
                    save=True,
                    show=False
                )
            except Exception: 
                print(f"Failed for storm {storm_name}, constituent {constituent}")
                raise

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["storm"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["storm"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("storm").reset_index(drop=True)

        out_path = f"HI_calculations/groundwater_hysteresis/summer/lawler_adapted_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_down Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Not enough data points to split the hydrograph for st1_up Turbidity FNU
Skipping st2_up: no valid Turbidity FNU data
Skipping st3_up: no valid Turbidity FNU data
Skipping st5_up: no valid Turbidity FNU data
Skipping st6_up: no valid Turbidity FNU data
Skipping st7_down: no valid Turbidity FNU data

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st1_down,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,st1_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,st2_down,2.691431,3.361477,3.861322,5.286291,29.502623,2.268324,1.678537,0.227115,0.383505,5.473403
3,st3_down,0.614657,-0.419908,0.890812,0.860771,0.811360,0.739754,0.646053,0.542404,0.402713,0.565402
4,st4_down,0.985740,0.982152,0.982774,0.971949,0.990348,0.992089,0.995153,1.000000,0.889096,0.976589
5,st4_up,0.979665,0.974888,0.967653,0.914277,0.876915,0.988046,0.993433,0.997639,0.947928,0.960049
6,st5_down,0.513059,0.472326,0.422842,0.346385,0.224352,-0.387035,0.647434,0.243324,0.136475,0.291018
7,st6_down,2.128378,1.306638,1.222115,1.157260,1.107544,1.067124,1.009535,0.854142,0.683725,1.170718
8,st7_up,0.911769,-0.196206,-0.504693,-0.668385,-0.893118,-0.918245,-0.133637,-0.091862,-0.106877,-0.289028

Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_down fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Not enough data points to split the hydrograph for st1_up fDOM RFU
Skipping st2_up: no valid fDOM RFU data
Skipping st3_up: no valid fDOM RFU data
Skipping st5_up: no valid fDOM RFU data
Skipping st6_up: no valid fDOM RFU data
Skipping st7_down: no valid fDOM RFU data

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st1_down,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,st1_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,st2_down,3.390328,4.563411,3.000301,-0.765520,-0.991155,0.472578,0.262457,-0.144275,-0.071505,1.079624
3,st3_down,-0.802232,-0.928452,-0.212603,-0.241746,-0.228879,-0.204837,-0.148925,-0.093230,-0.049246,-0.323350
4,st4_down,1.539341,1.306915,1.217499,1.120118,1.032774,1.009013,0.985909,0.974564,0.457341,1.071497
5,st4_up,0.671969,0.678874,0.684532,-0.222318,-0.706021,0.803575,0.793396,0.819222,0.192483,0.412857
6,st5_down,-0.177573,-0.281294,-0.383332,-0.495754,-0.613851,-0.853839,0.293327,0.135055,0.070202,-0.256340
7,st6_down,2.471055,0.987628,0.776384,0.619902,0.500310,0.458833,0.420692,0.223271,0.099165,0.728582
8,st7_up,0.316483,-0.926436,-0.944645,-0.962118,-0.949959,-0.981515,-0.299605,-0.230144,-0.137624,-0.568396

### Lloyd:
Turbidity and fDOM hysteresis

In [10]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []

    for storm_name, storm_df in sonde_events.items():
        if constituent not in storm_df.columns:
            continue

        row = {"storm": storm_name}

        for k in ks:
            result = calculate_lloyd_HI(
                storm_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=storm_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["storm"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["storm"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("storm").reset_index(drop=True)

        out_path = f"HI_calculations/summer_storms/lloyd_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st1_down,0.009821,-0.073544,-0.027333,0.071912,0.035096,0.056913,0.199870,0.611188,0.598638,0.164729
1,st1_up,0.010854,0.010775,0.019972,0.081883,0.100498,0.170613,0.453415,0.740972,0.625070,0.246006
2,st2_down,-0.101583,0.284299,0.344381,0.394449,0.415865,0.735543,0.681960,0.448731,0.405127,0.400975
3,st2_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,st3_down,-0.061447,-0.038599,0.088629,0.090477,0.049014,0.044816,0.007367,0.094706,0.191806,0.051863
5,st3_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,st4_down,-0.651017,0.112516,0.215087,0.193017,0.177033,0.258739,0.303984,0.221738,0.117380,0.105386
7,st4_up,-0.262695,0.058500,-0.093569,0.083092,0.338790,0.318386,0.361660,0.246520,0.134030,0.131635
8,st5_down,-0.007810,0.440381,0.450137,0.441303,0.462993,0.472043,0.378081,0.533371,0.570304,0.415645
9,st5_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,st6_down,0.160245,0.247730,0.261947,0.190078,0.206423,0.221927,-0.149667,-0.404455,-0.248152,0.054008
11,st6_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,st7_down,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,st7_up,-0.006383,0.183760,0.203632,0.214181,0.160634,0.220475,0.102967,-0.240755,-0.105978,0.081393

Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st1_down,-0.097542,-0.407592,-0.769576,-0.775293,-0.535504,-0.442949,-0.535596,-0.588749,-0.400157,-0.505884
1,st1_up,-0.036261,-0.349132,-0.680746,-0.709755,-0.572670,-0.533606,-0.595055,-0.642107,-0.469631,-0.509885
2,st2_down,-0.952241,-0.881216,-0.855705,-0.835382,-0.804771,-0.680454,-0.710767,-0.633219,-0.561056,-0.768312
3,st2_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,st3_down,-0.860086,-0.854339,-0.800664,-0.792267,-0.742584,-0.719064,-0.687695,-0.574766,-0.424727,-0.717355
5,st3_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,st4_down,-0.577111,-0.717785,-0.617440,-0.547792,-0.480792,-0.469849,-0.439952,-0.153194,-0.078389,-0.453590
7,st4_up,-0.647412,-0.498078,-0.624330,-0.440729,-0.481161,-0.404095,-0.369404,-0.142180,-0.072780,-0.408908
8,st5_down,-0.456522,-0.150125,-0.124870,-0.088380,-0.063765,-0.049239,-0.054069,0.133503,0.359674,-0.054866
9,st5_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,st6_down,-0.808890,-0.779969,-0.776427,-0.717095,-0.676437,-0.647539,-0.640526,-0.377679,-0.194842,-0.624378
11,st6_up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,st7_down,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,st7_up,-0.304983,-0.571091,-0.627993,-0.705240,-0.749339,-0.386260,-0.186662,0.138121,0.055137,-0.370923

Plot sonde data

In [11]:
for storm_name, storm_df in sonde_events.items():
    for constituent in ["Turbidity FNU", "fDOM RFU"]:
        if constituent not in storm_df.columns:
            continue

        results_list = []

        for k in ks:
            result = calculate_lloyd_HI(
                storm_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=storm_name,
                k=k
            )

            if result is not None:
                results_list.append(result)

        if results_list:
            plot_lloyd_hysteresis_multi_k(
                results_list,
                storm_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                out_dir="HI_calculations/summer_storms/lloyd_plots",
                save=True,
                show=False
            )

Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up Turbidity FNU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st2_up fDOM RFU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up Turbidity FNU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st3_up fDOM RFU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up Turbidity FNU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st5_up fDOM RFU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up Turbidity FNU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st6_up fDOM RFU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down Turbidity FNU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU
Not enough data points to split the hydrograph for st7_down fDOM RFU

Groundwater summer HI calculations

In [12]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []

    for storm_name, storm_df in sonde_events.items():
        results_list = []

        if constituent not in storm_df.columns:
            continue

        valid = storm_df[["P123_h_average", constituent]].dropna()
        if valid.empty:
            print(f"Skipping {storm_name}: no overlapping data")
            continue

        row = {"storm": storm_name}

        for k in ks:
            result = calculate_lloyd_HI(
                storm_df,
                tau_col="P123_h_average",
                constituent_col=constituent,
                storm_name=storm_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

            if result is not None:
                results_list.append(result)

        if results_list:
            try:
                plot_lloyd_hysteresis_multi_k(
                    results_list,
                    storm_df,
                    tau_col="P123_h_average",
                    constituent_col=constituent,
                    out_dir="HI_calculations/groundwater_hysteresis/summer/lloyd_plots",
                    save=True,
                    show=False
                )
            except Exception: 
                print(f"Failed for storm {storm_name}, constituent {constituent}")
                raise

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["storm"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["storm"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("storm").reset_index(drop=True)

        out_path = f"HI_calculations/groundwater_hysteresis/summer/lloyd_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

Skipping st1_down: no overlapping data
Skipping st1_up: no overlapping data
Skipping st2_up: no overlapping data
Skipping st3_up: no overlapping data
Skipping st5_up: no overlapping data
Skipping st6_up: no overlapping data
Skipping st7_down: no overlapping data

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st2_down,2.305769,1.766865,1.394596,1.018223,0.639464,0.733209,0.500077,0.067477,0.200926,0.958512
1,st3_down,0.134447,-0.040027,0.875146,0.775950,0.654456,0.521127,0.412176,0.316550,0.212648,0.429164
2,st4_down,0.743426,0.512646,0.449397,0.223069,0.512915,0.446419,0.408291,0.183146,0.000714,0.386669
3,st4_up,0.782790,0.542035,0.349304,0.100158,0.050620,0.398333,0.351484,0.217462,0.002035,0.310469
4,st5_down,0.358143,0.300555,0.242967,0.172322,0.091733,-0.119643,0.560657,0.102778,0.053154,0.195852
5,st6_down,0.584258,1.102389,1.142592,1.152535,1.087260,0.866910,0.369143,0.278493,0.213157,0.755193
6,st7_up,1.990595,-0.039060,-0.131942,-0.202626,-0.665194,-0.559110,-0.077678,-0.050858,-0.055432,0.023188

Skipping st1_down: no overlapping data
Skipping st1_up: no overlapping data
Skipping st2_up: no overlapping data
Skipping st3_up: no overlapping data
Skipping st5_up: no overlapping data
Skipping st6_up: no overlapping data
Skipping st7_down: no overlapping data

,storm,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,st2_down,0.584885,0.316492,0.122853,-0.063787,-0.246358,0.370760,0.206046,-0.133075,-0.069692,0.120903
1,st3_down,-0.680069,-0.823221,-0.196652,-0.235672,-0.226985,-0.203651,-0.145534,-0.089461,-0.046731,-0.294219
2,st4_down,0.229470,0.279122,0.283792,0.334279,0.661625,0.687947,0.704550,0.893553,0.034999,0.456593
3,st4_up,0.161059,0.190190,0.219826,-0.025044,-0.087540,0.553647,0.567259,0.715467,0.040540,0.259489
4,st5_down,-0.111560,-0.178181,-0.244801,-0.320452,-0.402621,-0.568139,0.288410,0.116394,0.057959,-0.151443
5,st6_down,0.173441,0.429052,0.395805,0.363083,0.331665,0.372957,0.398325,0.188893,0.084296,0.304169
6,st7_up,0.458332,-0.923794,-0.916719,-0.895489,-0.432966,-0.506083,-0.152166,-0.115110,-0.067628,-0.394625

# Spring Lloyd Sonde Calculations

Process and Merge Data

In [13]:
shear_stress = pd.read_csv('data/shear_stress/average_total_shear_stress_corrected.csv', parse_dates=['datetime'], index_col='datetime')
gw_head = pd.read_csv('data/groundwater/groundwater_head_full.csv', parse_dates=['Date_Time'], index_col='Date_Time')
sonde_downstream = pd.read_csv('data/sonde_data/sonde_down_full_record_smoothed.csv', parse_dates=['DateTime'], index_col='DateTime')
sonde_upstream = pd.read_csv('data/sonde_data/sonde_up_full_record_smoothed.csv', parse_dates=['DateTime'], index_col='DateTime')

# average rows with duplicate timestamps on sonde data (second-resolution data)
sonde_downstream = sonde_downstream.groupby(level=0).mean(numeric_only=True)
sonde_upstream = sonde_upstream.groupby(level=0).mean(numeric_only=True)

# only keep positive values in sonde data 
sonde_downstream = sonde_downstream[(sonde_downstream["Turbidity FNU"] > 0) & (sonde_downstream["fDOM RFU"] > 0)]
sonde_upstream = sonde_upstream[(sonde_upstream["Turbidity FNU"] > 0) & (sonde_upstream["fDOM RFU"] > 0)]


# re-sample shear stress and sonde data to 1 min intervals
shear_stress = shear_stress.resample('1min').interpolate()
groundwater_head = gw_head.resample('1min').interpolate()
sonde_downstream_resampled = sonde_downstream.resample('1min').interpolate()
sonde_upstream_resampled = sonde_upstream.resample('1min').interpolate()

# also join the sonde data with the shear stress data for the entire record 
sonde_downstream = sonde_downstream.join(shear_stress['shear_stress'], how="left")
sonde_upstream = sonde_upstream.join(shear_stress['shear_stress'], how="left")
# also join the sonde data with the groundwater head data for the entire record
sonde_downstream = sonde_downstream.join(groundwater_head['P123_h_average'], how="left")
sonde_upstream = sonde_upstream.join(groundwater_head['P123_h_average'], how="left")

Separating event by date and time

In [14]:
event_windows = {
    "down_event1": ("2023-04-17 13:00", "2023-04-18 11:00"),
    "down_event2": ("2023-04-18 11:00", "2023-04-19 10:00"),
    "down_event3": ("2023-04-19 10:00", "2023-04-20 11:00"),
    "down_event4": ("2023-04-21 12:00", "2023-04-22 09:30"),
    "down_event5": ("2023-04-22 14:00", "2023-04-23 10:30"),
    "down_event6": ("2023-04-23 11:30", "2023-04-24 11:00"),
    "down_event7": ("2023-04-24 11:00", "2023-04-25 11:00"),
    "down_event8": ("2023-04-27 12:00", "2023-04-28 12:00"),
    "down_event9": ("2023-04-29 12:00", "2023-04-30 12:00"),
    "down_event10": ("2023-04-30 12:00", "2023-05-01 11:00"),
    "down_event11": ("2023-05-01 11:00", "2023-05-02 13:00"),
    "down_event12": ("2023-05-02 13:00", "2023-05-03 11:30"),
    "down_event13": ("2023-05-03 11:30", "2023-05-04 10:00"),
    "down_event14": ("2023-05-04 11:00", "2023-05-05 09:00"),
    "down_event15": ("2023-05-05 10:00", "2023-05-06 09:00"),
    "up_event1": ("2023-04-17 13:00", "2023-04-18 11:00"),
    "up_event2": ("2023-04-18 11:00", "2023-04-19 10:00"),
    "up_event3": ("2023-04-19 10:00", "2023-04-20 11:00"),
    "up_event4": ("2023-04-21 12:00", "2023-04-22 09:30"),
    "up_event5": ("2023-04-22 14:00", "2023-04-23 10:30"),
    "up_event6": ("2023-04-23 11:30", "2023-04-24 11:00"),
    "up_event7": ("2023-04-24 11:00", "2023-04-25 11:00"),
    "up_event8": ("2023-04-27 12:00", "2023-04-28 12:00"),
    "up_event9": ("2023-04-29 12:00", "2023-04-30 12:00"),
    "up_event10": ("2023-04-30 12:00", "2023-05-01 11:00"),
    "up_event11": ("2023-05-01 11:00", "2023-05-02 13:00"),
    "up_event12": ("2023-05-02 13:00", "2023-05-03 11:30"),
    "up_event13": ("2023-05-03 11:30", "2023-05-04 10:00"),
    "up_event14": ("2023-05-04 11:00", "2023-05-05 09:00"),
    "up_event15": ("2023-05-05 10:00", "2023-05-06 09:00"),
}

# build event dictionary directly (no function)
sonde_events = {}
down = sonde_downstream.sort_index()   
up = sonde_upstream.sort_index()      

for event_name, (start, end) in event_windows.items():
    start = pd.Timestamp(start)
    end = pd.Timestamp(end)

    if "down" in event_name.lower():
        src = down
    elif "up" in event_name.lower():
        src = up
    else:
        continue
    sonde_events[event_name] = src.loc[(src.index >= start) & (src.index <= end)].copy()

Normalize shear stress and sonde data

In [15]:
sonde_constituents = ["Turbidity FNU", "fDOM RFU", "P123_h_average"]

for event_name, event_df in sonde_events.items():
    sonde_events[event_name] = normalize_storm_df(
        event_df,
        tau_col="shear_stress",
        constituent_cols=sonde_constituents
    )

### Lawler Adapted:
Turbidity and fDOM hysteresis

Calculate Lawler Adapted HI for sonde data

In [16]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []

    for event_name, event_df in sonde_events.items():
        if constituent not in event_df.columns:
            continue

        row = {"event": event_name}

        for k in ks:
            result = calculate_lawler_adapted_HI(
                event_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=event_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["event"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["event"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("event").reset_index(drop=True)

        out_path = f"HI_calculations/spring_events/lawler_adapted_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,0.657276,0.657906,0.864804,0.258779,0.178366,0.155325,0.092843,0.081080,-0.040355,0.322892
1,down_event10,0.206845,-0.258129,-0.946700,-0.839563,-0.442487,-0.486442,-0.416893,0.169088,0.314144,-0.300015
2,down_event11,-0.743957,0.127065,0.735611,0.710944,0.739524,0.694412,0.732646,0.664932,0.691315,0.483610
3,down_event12,-0.187313,0.486726,0.621608,0.186484,0.093645,0.227912,0.021411,-0.044462,-0.094632,0.145709
4,down_event13,-0.974837,-0.719443,0.655712,0.644591,0.781004,0.706929,0.723586,0.197523,0.071777,0.231871
5,down_event14,0.646114,0.799006,0.799320,0.774540,0.768651,0.695952,0.274714,0.142779,0.137902,0.559886
6,down_event15,0.995257,0.983722,0.961223,0.973002,0.960491,0.985111,0.990022,0.990323,0.991490,0.981182
7,down_event2,-0.794971,-0.143370,-0.426604,0.622810,0.886411,0.762918,0.425360,0.506882,0.439175,0.253179
8,down_event3,0.733575,0.729791,0.553201,0.670193,0.926292,0.120461,0.152779,-0.065062,-0.232708,0.398725
9,down_event4,-0.530208,-0.510176,0.274162,0.747419,0.723568,-0.393381,-0.064396,0.015072,-0.281316,-0.002139
10,down_event5,0.682431,0.671083,0.596740,0.682710,0.929470,0.979033,0.278064,0.523829,-0.057821,0.587282
11,down_event6,-0.683839,0.176536,0.813675,0.756197,0.778552,0.761064,0.899688,0.226267,-0.170479,0.395296
12,down_event7,-0.812371,-0.748132,-0.585511,-0.116278,0.555771,0.720742,0.403688,0.255357,0.210265,-0.012941
13,down_event8,0.098241,-0.027853,-0.162270,0.212258,0.335514,0.769808,0.770933,0.360231,0.139961,0.277425
14,down_event9,-0.844042,-0.661305,-0.613912,-0.607389,0.637314,0.428816,0.734348,0.169468,-0.333032,-0.121082
15,up_event1,-0.969681,-0.972725,-0.983436,-0.987836,-0.735821,-0.524276,-0.188640,-0.048812,0.119488,-0.587971
16,up_event10,-1.102840,-0.973658,-0.669836,0.124039,-0.136936,-0.533943,-0.536156,-0.098747,0.340678,-0.398600
17,up_event11,-0.684074,0.007067,0.536616,0.676619,0.971652,0.810989,0.816478,0.135605,0.243329,0.390476
18,up_event12,0.098261,0.441077,-0.282377,0.540141,0.478140,0.150312,0.080358,0.247052,0.177675,0.214515
19,up_event13,-0.693801,-0.664688,0.886125,0.855564,0.742424,0.653832,0.741051,0.402349,0.381692,0.367172
20,up_event14,0.217317,0.603038,0.840124,0.668932,0.804330,0.721164,0.044351,-0.175763,-0.132213,0.399031
21,up_event15,0.994519,0.986904,0.938041,0.929080,0.938134,0.971716,0.980854,0.980996,0.982514,0.966973
22,up_event2,-0.955370,-0.361387,0.974968,0.899543,0.968544,0.696612,0.698773,0.524926,0.718015,0.462736
23,up_event3,0.822333,-0.166345,0.334550,0.278043,0.912858,0.328490,-0.203071,-0.104516,-0.137980,0.229374
24,up_event4,-0.229111,-0.330676,0.232725,0.815403,0.699524,-0.053620,-0.058565,-0.206714,-0.407165,0.051311
25,up_event5,0.602724,0.578981,0.587404,0.668797,0.976687,0.393244,0.184348,0.528692,0.136475,0.517484
26,up_event6,-0.853678,-0.265543,-0.294617,0.215860,0.335826,0.497228,0.696862,0.892246,0.868534,0.232524
27,up_event7,-0.873065,-0.975694,0.959884,0.576403,0.527943,0.826795,0.615932,0.123936,-0.143557,0.182064
28,up_event8,-0.898601,-0.875676,-0.431281,0.304537,0.940818,0.651072,0.482905,0.645184,0.326859,0.127313
29,up_event9,-0.545045,-0.408024,-0.296586,-0.217807,0.445946,0.462687,-0.537297,0.369882,0.181187,-0.060562

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,0.836777,0.823743,0.664686,0.388779,0.228251,0.214477,0.211883,0.135931,-0.051479,0.383672
1,down_event10,-0.701548,-0.900637,-0.993255,-0.978431,-0.915436,-0.930632,-0.922480,-0.857931,-0.147090,-0.816382
2,down_event11,-0.967576,-0.964526,-0.483022,-0.441939,-0.111164,-0.101444,-0.011155,-0.134794,-0.005473,-0.357899
3,down_event12,-0.874736,0.240561,-0.127047,-0.453576,-0.441225,-0.398771,-0.397832,-0.373886,-0.340920,-0.351937
4,down_event13,-0.980929,-0.974310,-0.426106,-0.506843,-0.221643,-0.111751,0.120339,-0.080915,-0.032150,-0.357145
5,down_event14,-0.017876,-0.383363,0.054523,0.062479,0.120506,0.135667,-0.266640,-0.115346,-0.087345,-0.055266
6,down_event15,0.995840,0.994744,0.997881,0.998047,0.997788,0.993730,0.994215,0.994513,0.995033,0.995755
7,down_event2,-0.967648,-0.841825,-0.792511,-0.284116,-0.289590,-0.579297,-0.650043,-0.613087,-0.514765,-0.614765
8,down_event3,0.325364,0.456675,-0.330527,-0.235972,-0.310716,-0.573678,-0.503703,-0.439005,-0.333632,-0.216133
9,down_event4,-0.983066,-0.875043,-0.631816,-0.445005,-0.723412,-0.751419,-0.530392,-0.427962,-0.060886,-0.603222
10,down_event5,0.670023,0.505341,0.710385,0.693771,0.541354,0.547526,0.229179,0.180743,0.043272,0.457955
11,down_event6,-0.973659,-0.677159,-0.156603,-0.213765,-0.281733,-0.236962,-0.158501,-0.111420,0.061110,-0.305410
12,down_event7,-0.998319,-0.941175,-0.227482,-0.443393,-0.283887,-0.264335,-0.508580,-0.470775,-0.298595,-0.492949
13,down_event8,-0.985249,-0.952783,-0.882473,-0.690867,-0.167176,-0.141678,-0.334574,-0.064103,0.033568,-0.465037
14,down_event9,-0.887522,-0.872864,-0.853335,-0.830802,-0.234414,-0.490113,-0.519691,-0.415165,-0.288994,-0.599211
15,up_event1,-0.994562,-0.996366,-0.997728,-0.999645,-0.811886,-0.634786,-0.351449,-0.295608,-0.141268,-0.691478
16,up_event10,-0.701896,-0.715372,0.130384,0.790107,0.740121,0.855153,0.611071,-0.917597,-0.760915,0.003451
17,up_event11,-0.479789,0.338474,0.513063,0.533224,0.624087,0.689781,0.720941,-0.096248,0.270933,0.346052
18,up_event12,0.801060,-0.201907,0.262561,0.205642,0.251479,-0.669635,-0.245667,0.037671,0.096468,0.059741
19,up_event13,-0.975950,-0.986961,-0.896514,-0.202280,-0.023626,0.083968,0.228969,-0.125656,-0.140804,-0.337650
20,up_event14,-0.994767,-0.995363,-0.990135,-0.961646,-0.958024,-0.857389,-0.164346,0.103088,0.133884,-0.631633
21,up_event15,0.999804,0.999831,0.999842,0.999961,0.999786,0.998469,0.998356,0.998126,0.998365,0.999171
22,up_event2,-0.992301,-0.973258,-0.662276,-0.666781,-0.542711,-0.732417,-0.746184,-0.608139,-0.425126,-0.705466
23,up_event3,0.584449,-0.144487,-0.560911,-0.419996,-0.677729,-0.696508,-0.464943,-0.427900,-0.059892,-0.318657
24,up_event4,-0.996056,-0.860096,-0.863467,-0.581471,-0.760781,-0.788964,-0.768026,-0.442123,-0.091925,-0.683657
25,up_event5,0.859597,0.632396,0.781488,0.769947,0.646782,0.132188,0.301309,0.240324,0.062493,0.491836
26,up_event6,-0.999948,-0.933246,-0.862796,-0.016260,-0.154780,-0.229081,-0.159975,-0.284822,-0.017490,-0.406489
27,up_event7,-0.504825,-0.394308,-0.742764,-0.817761,-0.865833,0.364404,-0.206192,0.226285,0.344217,-0.288531
28,up_event8,-0.180042,-0.019576,0.513938,0.537129,0.612146,-0.647083,-0.713550,0.277411,-0.140191,0.026687
29,up_event9,-0.678276,-0.722237,-0.692492,-0.451567,0.592086,-0.190780,0.629615,0.159187,0.053320,-0.144572

Plot sonde data

In [17]:
for event_name, event_df in sonde_events.items():
    for constituent in ["Turbidity FNU", "fDOM RFU"]:
        if constituent not in event_df.columns:
            continue

        results_list = []

        for k in ks:
            result = calculate_lawler_adapted_HI(
                event_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=event_name,
                k=k
            )

            if result is not None:
                results_list.append(result)

        if results_list:
            plot_lloyd_hysteresis_multi_k(
                results_list,
                event_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                out_dir="HI_calculations/spring_events/lawler_adapted_plots",
                save=True,
                show=False
            )

Calculate groundwater lawler adapted HI

In [18]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []
    for event_name, event_df in sonde_events.items():
        results_list = []
        if constituent not in event_df.columns:
            continue
        # skip if no valid data for this constituent
        if event_df[constituent].dropna().empty:
            print(f"Skipping {event_name}: no valid {constituent} data")
            continue

        row = {"event": event_name}

        for k in ks:
            result = calculate_lawler_adapted_HI(
                event_df,
                tau_col="P123_h_average",
                constituent_col=constituent,
                storm_name=event_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

            if result is not None:
                results_list.append(result)

        if results_list:
            try:
                plot_lloyd_hysteresis_multi_k(
                    results_list,
                    event_df,
                    tau_col="P123_h_average",
                    constituent_col=constituent,
                    out_dir="HI_calculations/groundwater_hysteresis/spring/lawler_adapted_plots",
                    save=True,
                    show=False
                )
            except Exception: 
                print(f"Failed for event {event_name}, constituent {constituent}")
                raise

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["event"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["event"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("event").reset_index(drop=True)

        out_path = f"HI_calculations/groundwater_hysteresis/spring/lawler_adapted_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,-7.947182,-8.338234,-19.055348,-9.317390,-4.466916,-2.737220,-1.150687,-0.401642,0.342215,-5.896934
1,down_event10,0.744133,0.924809,0.929248,0.846424,0.766255,0.707164,0.602748,0.471188,0.277085,0.696562
2,down_event11,0.921861,-0.467447,0.576648,0.651374,0.743376,0.636620,-0.164831,-0.183164,-0.154996,0.284382
3,down_event12,-0.687906,-0.144525,0.122067,0.461737,0.334288,0.095101,-0.087071,-0.204336,-0.152041,-0.029187
4,down_event13,-0.893005,-0.962357,-0.875448,-0.721826,-0.687087,-0.666909,-0.387750,-0.259168,-0.187557,-0.626790
5,down_event14,0.445100,0.391049,-0.538308,-0.637328,-0.678921,-0.543520,-0.405444,-0.339143,-0.246834,-0.283705
6,down_event15,0.996964,0.996493,0.987280,0.985090,0.988420,0.987106,0.986245,0.985886,0.914372,0.980873
7,down_event2,-0.969921,-0.499028,-0.020275,0.091070,-0.548640,-0.402314,-0.284160,-0.184949,0.006687,-0.312392
8,down_event3,0.178950,0.588514,0.625937,-0.117430,0.075116,-0.020831,-0.105406,-0.108405,-0.056895,0.117728
9,down_event4,-0.226558,0.418497,-0.133804,0.129543,0.155197,0.548478,0.058679,0.186693,-0.034617,0.122456
10,down_event5,0.072623,-0.462185,0.368206,0.909869,0.826780,0.878502,0.651809,0.487401,0.434681,0.463076
11,down_event6,0.929762,0.743728,0.756702,0.574330,0.981638,0.248873,0.232290,0.036472,0.345125,0.538769
12,down_event7,11.118194,7.047560,2.901344,0.681805,0.415758,0.787489,0.680033,0.673774,0.599888,2.767316
13,down_event8,0.614460,0.876348,0.755837,0.700003,0.395359,-0.031476,0.275492,-0.108872,-0.574025,0.322569
14,down_event9,-0.555023,0.405874,0.205353,-0.015998,-0.198003,-0.149294,-0.511231,-0.543273,-0.631772,-0.221485
15,up_event1,-0.941850,-0.967683,-0.999569,-0.989443,-0.745932,-0.446713,-0.171442,0.128010,0.341869,-0.532528
16,up_event10,0.523474,0.851823,0.833623,0.690744,0.672589,0.301791,0.292010,-0.367211,-0.488481,0.367818
17,up_event11,0.695060,0.491113,0.770798,0.786271,0.800948,0.148513,0.307438,0.310230,0.167511,0.497542
18,up_event12,-0.475908,-0.279118,0.712582,0.226267,-0.112594,0.044356,-0.001834,-0.342931,-0.118544,-0.038636
19,up_event13,-0.271168,-0.467080,-0.754735,-0.829351,-0.854965,-0.770091,-0.364255,-0.313054,-0.153295,-0.530888
20,up_event14,0.403221,0.413223,-0.673007,-0.636140,-0.606924,-0.582151,-0.446017,-0.349382,-0.180885,-0.295340
21,up_event15,0.998887,0.999320,0.976116,0.958476,0.968518,0.972269,0.979579,0.549320,0.119683,0.835796
22,up_event2,0.940431,0.719733,-0.873424,-0.432344,-0.038614,0.313067,0.069260,0.069802,0.197487,0.107266
23,up_event3,0.960369,0.941138,0.952899,-0.532344,0.174295,-0.303623,-0.206226,-0.056749,-0.013131,0.212959
24,up_event4,0.540618,0.692636,0.521335,0.573380,0.402574,0.320568,0.352179,0.543806,-0.153619,0.421497
25,up_event5,0.195578,0.298385,0.454532,0.674258,0.795571,0.711333,0.362292,0.213668,-0.111103,0.399390
26,up_event6,0.593304,0.142612,0.371188,0.724864,0.737071,0.767002,0.823533,0.990875,0.724519,0.652774
27,up_event7,0.858329,0.461993,0.455303,0.510030,0.496642,0.744994,0.897769,0.833626,0.693069,0.661306
28,up_event8,0.485735,0.624095,0.422599,-0.231500,0.347231,0.240801,-0.093308,-0.105276,-0.155415,0.170551
29,up_event9,0.663715,0.765130,0.733048,0.588854,0.609988,0.636590,0.449846,0.052635,0.306297,0.534011

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,-157.294353,-47.066048,-11.866906,-9.262352,-6.357268,-4.036988,-1.585816,-0.546729,0.276432,-26.415559
1,down_event10,-0.255109,0.719506,0.863580,0.876568,0.863752,0.831705,0.779182,0.708265,0.596615,0.664896
2,down_event11,0.738756,-0.895233,-0.870479,0.169232,0.031985,-0.329698,-0.330398,-0.249643,-0.177843,-0.212591
3,down_event12,-0.348933,-0.370663,-0.371103,-0.648400,-0.740914,-0.826312,-0.832342,0.121152,0.039004,-0.442057
4,down_event13,-0.965751,-0.971980,-0.989410,-0.953334,-0.912655,-0.879794,-0.643420,-0.481653,-0.397302,-0.799478
5,down_event14,-0.918844,-0.967472,-0.950305,-0.895722,-0.894236,-0.836022,-0.681736,-0.455418,-0.295338,-0.766121
6,down_event15,0.995724,0.995667,0.994430,0.994935,0.993110,0.993181,0.994314,0.995064,0.967906,0.991592
7,down_event2,-0.641664,-0.878089,-0.855368,-0.838970,-0.770922,-0.740813,-0.606220,-0.539596,-0.396483,-0.696458
8,down_event3,0.417476,0.199685,0.054951,-0.400891,-0.488423,-0.222003,-0.151220,-0.091842,-0.045424,-0.080855
9,down_event4,-3.414318,-1.833226,-0.599738,0.302527,0.537962,0.620032,-0.636747,-0.582282,-0.376746,-0.664726
10,down_event5,-0.952624,-0.790612,-0.543872,-0.492008,-0.435010,-0.411764,-0.357806,-0.242655,-0.204606,-0.492329
11,down_event6,-0.504365,-0.214456,-0.290430,-0.229310,-0.297413,-0.288734,-0.272322,-0.224059,-0.191531,-0.279180
12,down_event7,3.868456,2.696985,1.438867,0.445721,-0.112817,-0.227106,-0.245220,-0.335929,-0.438684,0.787808
13,down_event8,0.314451,0.698572,0.820302,0.831082,0.788743,0.760137,0.720885,0.700065,0.650462,0.698300
14,down_event9,-0.354899,0.323788,0.697788,0.733055,0.707535,0.622323,0.467826,0.333003,0.160635,0.410117
15,up_event1,-0.992614,-0.996323,-0.998623,-0.999945,-0.804544,-0.607713,-0.418586,-0.014712,0.069770,-0.640366
16,up_event10,0.804071,0.900542,0.390745,0.821387,0.300356,0.710078,0.523636,-0.027784,0.911481,0.592723
17,up_event11,0.474468,0.360055,-0.567017,0.571526,0.645445,-0.428274,-0.420420,0.324470,0.197888,0.128682
18,up_event12,0.240947,0.288910,0.890282,-0.347614,-0.434321,-0.514441,-0.746375,0.664979,0.282117,0.036054
19,up_event13,-0.987468,-0.969182,-0.977010,-0.981025,-0.965409,-0.918032,-0.608059,-0.559174,-0.418238,-0.820400
20,up_event14,-0.995432,-0.996572,-0.978612,-0.984816,-0.983848,-0.928710,-0.670168,-0.570205,-0.359580,-0.829771
21,up_event15,0.999512,0.999604,0.999650,0.999693,0.999620,0.998710,0.997978,0.692498,0.211901,0.877685
22,up_event2,-0.126772,-0.919579,-0.975903,-0.986265,-0.929335,-0.865166,-0.678917,-0.554261,-0.219730,-0.695103
23,up_event3,0.903514,0.688628,0.087880,-0.893183,-0.886488,-0.413736,-0.328865,-0.243640,-0.132923,-0.135424
24,up_event4,-0.856697,-0.920185,-0.963153,-0.985805,-0.997451,-0.999816,-0.862847,-0.592767,-0.365640,-0.838262
25,up_event5,-0.959180,-0.697993,-0.591589,-0.485756,-0.455904,-0.430636,-0.389794,-0.303000,-0.316930,-0.514531
26,up_event6,-0.784164,0.103914,-0.144809,-0.271004,-0.388967,-0.450817,-0.505760,-0.492215,-0.424515,-0.373148
27,up_event7,6.887321,-0.593691,-0.881181,-0.456024,0.275599,-0.364851,-0.052826,0.174733,0.149331,0.570934
28,up_event8,0.474304,-1.000000,0.304719,0.378076,0.073914,0.432206,0.458971,0.281325,-0.247826,0.128410
29,up_event9,0.821902,0.726527,0.875707,0.587909,0.386337,0.865441,0.886178,0.874908,0.533212,0.728680

### Lloyd:

Turbidity and fDOM hysteresis

In [19]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []

    for event_name, event_df in sonde_events.items():
        if constituent not in event_df.columns:
            continue

        row = {"event": event_name}

        for k in ks:
            result = calculate_lloyd_HI(
                event_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=event_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["event"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["event"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("event").reset_index(drop=True)

        out_path = f"HI_calculations/spring_events/lloyd_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,0.499408,0.499887,0.657091,0.196624,0.135525,0.118018,0.070544,0.061606,-0.031952,0.245195
1,down_event10,0.018170,-0.020807,-0.071063,-0.086296,-0.056348,-0.103921,-0.106974,0.061359,0.275022,-0.010095
2,down_event11,-0.145994,0.029803,0.220895,0.225296,0.250811,0.324016,0.396615,0.497568,0.669136,0.274238
3,down_event12,-0.103412,0.301101,0.425305,0.105007,0.060038,0.154843,0.014577,-0.032018,-0.077980,0.094162
4,down_event13,-0.413528,-0.329870,0.136951,0.244977,0.467399,0.570261,0.715846,0.189403,0.059800,0.182360
5,down_event14,0.149328,0.203332,0.302456,0.442600,0.510843,0.596114,0.240641,0.107292,0.105124,0.295303
6,down_event15,0.622495,0.548601,0.562616,0.950949,0.623617,0.547605,0.811939,0.827870,0.940647,0.715149
7,down_event2,-0.245760,-0.046732,-0.147300,0.163547,0.330114,0.375702,0.235038,0.364337,0.425622,0.161619
8,down_event3,0.432584,0.591572,0.220264,0.376961,0.608978,0.090008,0.131882,-0.060366,-0.224689,0.240799
9,down_event4,-0.240017,-0.223119,0.067488,0.248358,0.283826,-0.253024,-0.044285,0.010664,-0.239228,-0.043260
10,down_event5,0.564422,0.551333,0.337985,0.401458,0.410609,0.420647,0.071036,0.140255,-0.004504,0.321471
11,down_event6,-0.462369,0.138199,0.812554,0.711967,0.663576,0.690851,0.740031,0.197641,-0.146361,0.371788
12,down_event7,-0.588211,-0.556655,-0.203989,-0.025142,0.234748,0.432956,0.270388,0.240176,0.175103,-0.002292
13,down_event8,0.018250,-0.005898,-0.038110,0.073378,0.113412,0.608044,0.688710,0.173637,0.086221,0.190849
14,down_event9,-0.181711,-0.135259,-0.172247,-0.248410,0.198631,0.204872,0.436981,0.116150,-0.327874,-0.012097
15,up_event1,-0.477530,-0.520201,-0.454476,-0.441427,-0.367423,-0.284764,-0.089482,-0.026241,0.076213,-0.287259
16,up_event10,-0.090586,-0.081633,-0.050804,0.007136,-0.024539,-0.210080,-0.241315,-0.039551,0.310413,-0.046773
17,up_event11,-0.475522,0.001921,0.313962,0.446296,0.887843,0.793553,0.768574,0.122609,0.204746,0.340442
18,up_event12,0.033056,0.216309,-0.187846,0.260298,0.207122,0.076312,0.063115,0.244221,0.166685,0.119919
19,up_event13,-0.291185,-0.299429,0.111220,0.294183,0.455162,0.538023,0.710462,0.347379,0.325211,0.243447
20,up_event14,0.063298,0.177479,0.288645,0.442355,0.563596,0.718039,0.043930,-0.164752,-0.116688,0.223989
21,up_event15,0.486172,0.482170,0.458033,0.456231,0.512316,0.474340,0.693818,0.685477,0.731354,0.553323
22,up_event2,-0.261229,-0.099991,0.309036,0.322188,0.443253,0.336794,0.345961,0.342095,0.715196,0.272589
23,up_event3,0.217555,-0.041706,0.041243,0.062244,0.246610,0.179631,-0.175146,-0.090923,-0.119674,0.035537
24,up_event4,-0.094066,-0.176255,0.081057,0.556052,0.537352,-0.046712,-0.054790,-0.196553,-0.372508,0.025953
25,up_event5,0.484944,0.537967,0.495818,0.545963,0.873779,0.324561,0.115501,0.375631,0.036679,0.421205
26,up_event6,-0.655025,-0.189687,-0.194853,0.102719,0.156833,0.244478,0.589601,0.844429,0.508997,0.156388
27,up_event7,-0.501410,-0.610363,0.222193,0.248920,0.240932,0.640830,0.548934,0.121362,-0.136199,0.086133
28,up_event8,-0.398485,-0.393488,-0.219753,0.106666,0.711798,0.516275,0.362981,0.391934,0.221791,0.144413
29,up_event9,-0.359988,-0.270809,-0.196136,-0.143112,0.249093,0.230373,-0.226415,0.311605,0.179743,-0.025072

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,0.763179,0.751291,0.606223,0.354584,0.208175,0.195613,0.193247,0.123976,-0.049499,0.349643
1,down_event10,-0.212334,-0.285554,-0.357836,-0.384952,-0.502447,-0.826943,-0.865974,-0.844559,-0.145045,-0.491738
2,down_event11,-0.693113,-0.699896,-0.067884,-0.076059,-0.025605,-0.043328,-0.004892,-0.087287,-0.004779,-0.189205
3,down_event12,-0.818404,0.033496,-0.020938,-0.321173,-0.342378,-0.384235,-0.397346,-0.372648,-0.336687,-0.328924
4,down_event13,-0.877771,-0.888842,-0.052842,-0.168220,-0.092776,-0.075202,0.103559,-0.080484,-0.031807,-0.240487
5,down_event14,-0.001800,-0.061866,0.009797,0.023019,0.050707,0.093696,-0.265518,-0.114883,-0.086001,-0.039205
6,down_event15,0.853406,0.854545,0.863077,0.890961,0.869950,0.854824,0.909551,0.940793,0.971434,0.889838
7,down_event2,-0.950259,-0.830217,-0.767657,-0.092985,-0.111853,-0.413641,-0.569018,-0.592853,-0.498632,-0.536346
8,down_event3,0.121530,0.181421,-0.119505,-0.088886,-0.144211,-0.516913,-0.503014,-0.397573,-0.301125,-0.196475
9,down_event4,-0.440649,-0.397282,-0.119285,-0.087187,-0.262955,-0.344766,-0.244274,-0.197386,-0.028234,-0.235780
10,down_event5,0.201165,0.168211,0.454736,0.466981,0.438195,0.471523,0.223035,0.174930,0.036596,0.292819
11,down_event6,-0.943387,-0.656716,-0.069766,-0.110604,-0.163503,-0.140246,-0.112849,-0.095754,0.060965,-0.247985
12,down_event7,-0.941114,-0.925321,-0.061087,-0.175758,-0.118750,-0.127915,-0.398106,-0.407340,-0.285916,-0.382367
13,down_event8,-0.721450,-0.724686,-0.707110,-0.597947,-0.062823,-0.069990,-0.240650,-0.060138,0.033370,-0.350158
14,down_event9,-0.874021,-0.868465,-0.840836,-0.805255,-0.058006,-0.183002,-0.223186,-0.403298,-0.282105,-0.504241
15,up_event1,-0.781103,-0.830913,-0.846025,-0.866117,-0.727510,-0.585435,-0.273700,-0.282573,-0.138448,-0.592425
16,up_event10,-0.452590,-0.402160,0.034018,0.303582,0.510765,0.634680,0.328310,-0.671221,-0.404836,-0.013272
17,up_event11,-0.182381,0.062226,0.124325,0.146837,0.252491,0.326230,0.387395,-0.064085,0.168987,0.135781
18,up_event12,0.073718,-0.021350,0.024220,0.053415,0.075145,-0.661912,-0.177911,0.027108,0.070917,-0.059628
19,up_event13,-0.776331,-0.819114,-0.125145,-0.040630,-0.006700,0.049654,0.191747,-0.121989,-0.134360,-0.198096
20,up_event14,-0.708499,-0.489346,-0.464880,-0.846350,-0.871441,-0.454349,-0.014829,0.009691,0.012888,-0.425235
21,up_event15,0.832709,0.837615,0.842508,0.871965,0.909482,0.843768,0.820210,0.749988,0.894726,0.844774
22,up_event2,-0.953430,-0.940399,-0.132821,-0.179461,-0.211382,-0.545070,-0.674932,-0.592237,-0.424246,-0.517109
23,up_event3,0.085324,-0.017848,-0.117884,-0.093578,-0.308956,-0.662278,-0.441917,-0.401782,-0.056062,-0.223887
24,up_event4,-0.976572,-0.223285,-0.319252,-0.226321,-0.593375,-0.777342,-0.759090,-0.438620,-0.091471,-0.489481
25,up_event5,0.189366,0.164870,0.411875,0.421691,0.448489,0.096230,0.274175,0.212887,0.045639,0.251691
26,up_event6,-1.047428,-0.970803,-0.891274,-0.003001,-0.037499,-0.068718,-0.066853,-0.204289,-0.016278,-0.367349
27,up_event7,-0.087577,-0.057914,-0.268134,-0.456086,-0.748248,0.046836,-0.035366,0.041602,0.089985,-0.163878
28,up_event8,-0.065435,-0.008473,0.373257,0.391359,0.390142,-0.359780,-0.207775,0.255760,-0.130688,0.070930
29,up_event9,-0.425007,-0.457847,-0.383558,-0.200913,0.271247,-0.118156,0.446460,0.082096,0.041807,-0.082652

Plot sonde data

In [20]:
for event_name, event_df in sonde_events.items():
    for constituent in ["Turbidity FNU", "fDOM RFU"]:
        if constituent not in event_df.columns:
            continue

        results_list = []

        for k in ks:
            result = calculate_lloyd_HI(
                event_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                storm_name=event_name,
                k=k
            )

            if result is not None:
                results_list.append(result)

        if results_list:
            plot_lloyd_hysteresis_multi_k(
                results_list,
                event_df,
                tau_col="shear_stress",
                constituent_col=constituent,
                out_dir="HI_calculations/spring_events/lloyd_plots",
                save=True,
                show=False
            )

Groundwater Lloyd HI calculation

In [21]:
ks = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
sonde_constituents = ["Turbidity FNU", "fDOM RFU"]

for constituent in sonde_constituents:
    summary_rows = []
    for event_name, event_df in sonde_events.items():
        results_list = []
        if constituent not in event_df.columns:
            continue
        # skip if no valid data for this constituent
        if event_df[constituent].dropna().empty:
            print(f"Skipping {event_name}: no valid {constituent} data")
            continue

        row = {"event": event_name}

        for k in ks:
            result = calculate_lloyd_HI(
                event_df,
                tau_col="P123_h_average",
                constituent_col=constituent,
                storm_name=event_name,
                k=k
            )

            col_name = f"HI{int(k * 100)}"
            row[col_name] = np.nan if result is None else result["HI"]

            if result is not None:
                results_list.append(result)

        if results_list:
            try:
                plot_lloyd_hysteresis_multi_k(
                    results_list,
                    event_df,
                    tau_col="P123_h_average",
                    constituent_col=constituent,
                    out_dir="HI_calculations/groundwater_hysteresis/spring/lloyd_plots",
                    save=True,
                    show=False
                )
            except Exception: 
                print(f"Failed for event {event_name}, constituent {constituent}")
                raise

        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)

    if not summary_df.empty:
        hi_cols = [f"HI{int(k * 100)}" for k in ks]
        summary_df = summary_df[["event"] + hi_cols]
        summary_df["HI_avg"] = summary_df[hi_cols].mean(axis=1, skipna=True)
        summary_df = summary_df[["event"] + hi_cols + ["HI_avg"]]
        summary_df = summary_df.sort_values("event").reset_index(drop=True)

        out_path = f"HI_calculations/groundwater_hysteresis/spring/lloyd_{constituent.replace(' ', '_').replace('/', '_').lower()}_hysteresis_summary.csv"
        summary_df.to_csv(out_path, index=False)

        display(summary_df)

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,-3.343925,-2.785495,-2.089355,-1.689289,-1.335160,-0.889502,-0.708739,-0.254341,0.338466,-1.417482
1,down_event10,0.147313,0.623006,0.665267,0.279170,0.166049,0.122320,0.076855,0.045133,0.019415,0.238281
2,down_event11,0.851227,-0.041290,0.119000,0.310284,0.456768,0.406279,-0.157181,-0.182907,-0.153155,0.178780
3,down_event12,-0.112510,-0.024821,0.029638,0.148193,0.137100,0.047365,-0.057076,-0.136685,-0.095148,-0.007105
4,down_event13,-0.108829,-0.225713,-0.656188,-0.572072,-0.558440,-0.611750,-0.374479,-0.220683,-0.149579,-0.386415
5,down_event14,0.124046,0.106507,-0.355627,-0.470254,-0.488689,-0.410256,-0.301364,-0.290857,-0.226501,-0.256999
6,down_event15,0.850538,0.713040,0.873373,0.900274,0.699225,0.622883,0.578886,0.570569,0.794196,0.733665
7,down_event2,-0.176528,-0.120712,-0.007067,0.029950,-0.292288,-0.216270,-0.228555,-0.148600,0.005703,-0.128263
8,down_event3,0.043972,0.157463,0.181143,-0.041411,0.024286,-0.016743,-0.091293,-0.092724,-0.044930,0.013307
9,down_event4,-0.038523,0.074443,-0.034641,0.035057,0.049196,0.199293,0.032665,0.132414,-0.021197,0.047634
10,down_event5,0.011494,-0.222625,0.254991,0.786857,0.812766,0.787791,0.415616,0.254687,0.189512,0.365677
11,down_event6,0.836660,0.739357,0.648028,0.500368,0.798641,0.203645,0.200502,0.032189,0.304281,0.473741
12,down_event7,1.561787,1.064761,0.619597,0.217691,0.203320,0.458023,0.468640,0.575682,0.594531,0.640448
13,down_event8,0.197073,0.876348,0.382781,0.288527,0.080853,-0.003892,0.047018,-0.013462,-0.070980,0.198252
14,down_event9,-0.212894,0.262038,0.099124,-0.006136,-0.075949,-0.057266,-0.196096,-0.208387,-0.242333,-0.070878
15,up_event1,-0.434487,-0.417302,-0.498050,-0.468870,-0.414773,-0.228758,-0.088021,0.072639,0.242560,-0.248340
16,up_event10,0.143558,0.751252,0.654776,0.291889,0.268456,0.056486,0.053900,-0.047988,-0.063836,0.234277
17,up_event11,0.583806,0.108356,0.264877,0.765589,0.764953,0.139071,0.282163,0.278944,0.143960,0.370191
18,up_event12,-0.201189,-0.091252,0.599595,0.059661,-0.037063,0.015236,-0.000943,-0.207770,-0.074143,0.006904
19,up_event13,-0.045975,-0.111877,-0.405816,-0.732829,-0.732367,-0.649072,-0.334953,-0.281684,-0.117975,-0.379172
20,up_event14,0.117429,0.121093,-0.606881,-0.516547,-0.472735,-0.448628,-0.441451,-0.349268,-0.178835,-0.308425
21,up_event15,0.703291,0.620873,0.529096,0.499567,0.591670,0.543340,0.595179,0.288496,0.088418,0.495548
22,up_event2,0.925694,0.227820,-0.134993,-0.112128,-0.012864,0.122672,0.033285,0.034854,0.187968,0.141368
23,up_event3,1.693681,1.105631,0.558388,-0.098558,0.023174,-0.248105,-0.145730,-0.034288,-0.007897,0.316255
24,up_event4,0.188897,0.246887,0.150135,0.159867,0.127600,0.098250,0.181806,0.538576,-0.123258,0.174307
25,up_event5,0.114206,0.188402,0.346402,0.648098,0.722883,0.620596,0.313117,0.180278,-0.110709,0.335919
26,up_event6,0.333025,0.069731,0.176987,0.475349,0.536429,0.671132,0.747646,0.911526,0.712957,0.514976
27,up_event7,0.314861,0.198495,0.179182,0.207412,0.274697,0.558602,0.813183,0.829320,0.648685,0.447160
28,up_event8,0.269759,0.474173,0.209033,-0.066117,0.151923,0.090587,-0.026649,-0.030067,-0.044387,0.114251
29,up_event9,0.370109,0.610892,0.514938,0.268576,0.293291,0.328487,0.153333,0.010419,0.082799,0.292538

,event,HI10,HI20,HI30,HI40,HI50,HI60,HI70,HI80,HI90,HI_avg
0,down_event1,-4.824191,-4.150932,-3.638570,-2.915994,-2.219520,-1.514849,-1.106693,-0.388342,0.276113,-2.275886
1,down_event10,-0.031200,0.313716,0.774196,0.868527,0.775325,0.604399,0.431547,0.296916,0.180883,0.468257
2,down_event11,0.282698,-0.200123,-0.253488,0.066184,0.015318,-0.245558,-0.290524,-0.199430,-0.131965,-0.106321
3,down_event12,-0.062932,-0.070386,-0.071747,-0.227356,-0.342959,-0.590593,-0.677692,0.115738,0.034796,-0.210348
4,down_event13,-0.435426,-0.635924,-0.979284,-0.933586,-0.881963,-0.827190,-0.581024,-0.336264,-0.260277,-0.652326
5,down_event14,-0.364647,-0.391537,-0.949896,-0.854735,-0.836046,-0.741150,-0.591715,-0.306921,-0.190247,-0.580766
6,down_event15,0.923494,0.868517,0.846249,0.879832,0.862508,0.853136,0.847426,0.859598,0.899885,0.871183
7,down_event2,-0.473449,-0.787787,-0.767950,-0.800541,-0.754041,-0.737439,-0.482046,-0.411589,-0.282581,-0.610825
8,down_event3,0.231651,0.100067,0.024583,-0.263377,-0.347378,-0.119199,-0.076230,-0.044297,-0.021136,-0.057257
9,down_event4,-0.648162,-0.377841,-0.172100,0.121450,0.370140,0.604304,-0.276115,-0.256614,-0.172430,-0.089708
10,down_event5,-0.389304,-0.379119,-0.312322,-0.342648,-0.336134,-0.355207,-0.336412,-0.234826,-0.204368,-0.321149
11,down_event6,-0.353753,-0.106824,-0.171660,-0.145694,-0.227547,-0.241424,-0.248170,-0.210823,-0.186896,-0.210310
12,down_event7,0.803895,0.553185,0.328048,0.118979,-0.040305,-0.102583,-0.126768,-0.205699,-0.383919,0.104982
13,down_event8,0.073438,0.371051,0.730861,0.787721,0.597766,0.507382,0.413512,0.373694,0.297943,0.461485
14,down_event9,-0.091804,0.123862,0.597270,0.710352,0.625798,0.426241,0.227400,0.129147,0.049505,0.310863
15,up_event1,-0.842572,-0.857951,-0.884218,-0.903480,-0.745102,-0.573184,-0.402436,-0.011169,0.065371,-0.572749
16,up_event10,0.351429,0.775367,0.054921,0.393801,0.036762,0.209733,0.094131,-0.002379,0.881764,0.310614
17,up_event11,0.108099,0.068671,-0.235027,0.275059,0.331473,-0.408885,-0.419369,0.198062,0.124139,0.004691
18,up_event12,0.024840,0.031644,0.608571,-0.065159,-0.083476,-0.101930,-0.223025,0.664469,0.191661,0.116400
19,up_event13,-0.304700,-0.597630,-0.834106,-0.717192,-0.779083,-0.783518,-0.388819,-0.357116,-0.224620,-0.554087
20,up_event14,-0.955744,-0.913678,-0.086915,-0.097034,-0.095335,-0.087127,-0.050514,-0.043168,-0.024313,-0.261537
21,up_event15,0.885726,0.941179,0.820212,0.859691,0.702292,0.762046,0.716205,0.558279,0.158642,0.711586
22,up_event2,-0.080523,-0.771821,-0.884803,-0.936632,-0.913861,-0.859842,-0.512586,-0.407360,-0.143046,-0.612275
23,up_event3,1.390730,0.661965,0.033686,-0.665829,-0.706069,-0.227697,-0.168975,-0.118392,-0.059891,0.015503
24,up_event4,-0.347063,-0.424755,-0.555022,-0.646494,-0.696382,-0.808787,-0.801873,-0.559418,-0.359411,-0.577689
25,up_event5,-0.303881,-0.262000,-0.292067,-0.281284,-0.318311,-0.321760,-0.327072,-0.271303,-0.311457,-0.298793
26,up_event6,-0.384726,0.016508,-0.036456,-0.097875,-0.193087,-0.296369,-0.417515,-0.467782,-0.419426,-0.255192
27,up_event7,0.647376,-0.140005,-0.768917,-0.091895,0.033325,-0.072971,-0.007667,0.026999,0.030256,-0.038167
28,up_event8,0.379016,-0.420084,0.184109,0.255374,0.033528,0.319768,0.356369,0.164441,-0.104108,0.129824
29,up_event9,0.312844,0.180096,0.477613,0.096712,0.042678,0.436002,0.527790,0.474131,0.077436,0.291700