In [26]:
# testing hysteresis parameter calculation? 
import numpy as np
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

sonde_downstream = pd.read_csv('../../data/sonde_data/sonde_down_full_record_smoothed.csv', parse_dates=['DateTime'], index_col='DateTime')
sonde_upstream = pd.read_csv('../../data/sonde_data/sonde_up_full_record_smoothed.csv', parse_dates=['DateTime'], index_col='DateTime')

spring_sample_times = pd.read_csv('spring_sample_times.csv', parse_dates=['Date'], index_col='Date')
summer_sample_times = pd.read_csv('summer_sample_times.csv', parse_dates=['Date'], index_col='Date')

# average rows with duplicate timestamps on sonde data (second-resolution data)
sonde_downstream = sonde_downstream.groupby(level=0).mean(numeric_only=True)
sonde_upstream = sonde_upstream.groupby(level=0).mean(numeric_only=True)

sonde_downstream_resampled = sonde_downstream.resample('1min').interpolate()
sonde_upstream_resampled = sonde_upstream.resample('1min').interpolate()

In [27]:
# downstream sonde join
spring_sample_times = spring_sample_times.join(sonde_downstream_resampled, how="left")
summer_sample_times = summer_sample_times.join(sonde_downstream_resampled, how="left")
# change the column names to indicate that these are downstream sonde data (except for the first one)
spring_sample_times.columns = [spring_sample_times.columns[0], *[f"{col}_downstream" for col in spring_sample_times.columns[1:]]]
summer_sample_times.columns = [summer_sample_times.columns[0], *[f"{col}_downstream" for col in summer_sample_times.columns[1:]]]

In [28]:
spring_sample_times

                           Site  Turbidity FNU_downstream  fDOM RFU_downstream
Date
2023-04-15 12:30:00  Downstream                  6.369539            14.260796
2023-04-15 16:30:00  Downstream                  6.368628            14.256059
2023-04-15 20:30:00  Downstream                  6.367717            14.251321
2023-04-16 00:30:00  Downstream                  6.366805            14.246583
2023-04-16 12:30:00  Downstream                  6.364071            14.232370
...                         ...                       ...                  ...
2023-05-05 05:00:00    Upstream                  8.913391             0.656824
2023-05-05 08:00:00    Upstream                  7.568120             0.635903
2023-05-05 11:00:00    Upstream                  7.663717             0.584799
2023-05-05 14:00:00    Upstream                 10.371967             0.572386
2023-05-05 17:00:00    Upstream                 10.963209             0.669160

[166 rows x 3 columns]

In [29]:
# upstream sonde join
spring_sample_times = spring_sample_times.join(sonde_upstream_resampled, how="left")
summer_sample_times = summer_sample_times.join(sonde_upstream_resampled, how="left")
# change the upstream sonde column names to indicate that these are upstream sonde data (except for the first three)
spring_sample_times.columns = [*spring_sample_times.columns[:3], *[f"{col}_upstream" for col in spring_sample_times.columns[3:]]]
summer_sample_times.columns = [*summer_sample_times.columns[:3], *[f"{col}_upstream" for col in summer_sample_times.columns[3:]]]

In [30]:
spring_sample_times

,Site,Turbidity FNU_downstream,fDOM RFU_downstream,Turbidity FNU_upstream,fDOM RFU_upstream
Date,,,,,
2023-04-15 12:30:00,Downstream,6.369539,14.260796,3.939949,3.761170
2023-04-15 16:30:00,Downstream,6.368628,14.256059,3.940472,3.760005
2023-04-15 20:30:00,Downstream,6.367717,14.251321,3.940994,3.758840
2023-04-16 00:30:00,Downstream,6.366805,14.246583,3.941516,3.757674
2023-04-16 12:30:00,Downstream,6.364071,14.232370,3.943083,3.754178
...,...,...,...,...,...
2023-05-05 05:00:00,Upstream,8.913391,0.656824,5.489712,1.621931
2023-05-05 08:00:00,Upstream,7.568120,0.635903,8.273220,1.958466
2023-05-05 11:00:00,Upstream,7.663717,0.584799,6.576419,1.849539
2023-05-05 14:00:00,Upstream,10.371967,0.572386,7.379180,1.756351
2023-05-05 17:00:00,Upstream,10.963209,0.669160,9.817265,1.985760

In [31]:
# export to csv
spring_sample_times.to_csv('spring_sample_times_with_sonde.csv')
summer_sample_times.to_csv('summer_sample_times_with_sonde.csv')